name: "Steampunk Spotter"
description: "Scan your Ansible content using Steampunk Spotter."
author: "XLAB Steampunk"
branding:
  icon: "target"
  color: "red"
inputs:
  paths:
    description: "List of paths to Ansible content files to be scanned. If not specified, the whole repository is scanned."
    required: false
    default: "."
  project_id:
    description: "ID of an existing target project in the app, where the scan result will be stored. If not specified, the first project of the user's first organization (in the app) will be used."
    required: false
  include_values:
    description: "Parses and uploads values from Ansible task parameters to the backend."
    required: false
    default: "false"
  include_metadata:
    description: "Uploads metadata (i.e., file names, line and column numbers) to the backend."
    required: false
    default: "false"
  display_level:
    description: "Displays check results with specified level or greater (e.g., warning will show all warnings and errors, but suppress hints). Available options: hint, warning, error."
    required: false
    default: "hint"
  no_docs_url:
    description: "Omits documentation URLs from the output."
    required: false
    default: "false"
  ansible_version:
    description: "Ansible version to use for scanning. If not specified, all Ansible versions are considered for scanning."
    required: false
  profile:
    description: "Sets profile with selected set of checks to be used for scanning."
    required: false
    default: "default"
  custom_policies_path:
    description: "Path to the file or folder with custom OPA policies written in Rego Language (enterprise feature)."
    required: false
  custom_policies_clear:
    description: "Clears OPA policies for custom Spotter checks after scanning (enterprise feature)."
    required: false
    default: "false"
outputs:
  output:
    description: "Output from scanning (from spotter scan CLI command)."
runs:
  using: "docker"
  image: "docker://ghcr.io/xlab-steampunk/spotter-action:latest"
  args:
    - ${{ inputs.paths }}
    - ${{ inputs.project_id }}
    - ${{ inputs.include_values }}
    - ${{ inputs.include_metadata }}
    - ${{ inputs.display_level }}
    - ${{ inputs.no_docs_url }}
    - ${{ inputs.ansible_version }}
    - ${{ inputs.profile }}
    - ${{ inputs.custom_policies_path }}
    - ${{ inputs.custom_policies_clear }}
