name: 'Steampunk Spotter'
description: 'Scan your Ansible content using Steampunk Spotter.'
author: 'XLAB Steampunk'
branding:
  icon: "target"
  color: "red"
inputs:
  cli_version:
    description: 'The version of the Steampunk Spotter CLI. If not provided, the latest version is used.'
    required: false
  paths:
    description: 'List of paths to Ansible content files to be scanned. If not provided, the whole repository is scanned.'
    required: false
    default: "."
  parse_values:
    description: 'If true, it parses values from Ansible task parameters and sends them for scanning.'
    required: false
    default: "false"
  display_level:
    description: 'Displays check results with specified level or greater (e.g., warning will show all warnings and errors, but suppress hints). Available options: hint, warning, error.'
    required: false
    default: "hint"
  ansible_version:
    description: 'Ansible version to use for scanning. If not provided, all Ansible versions are considered for scanning.'
    required: false
outputs:
  output:
    description: 'Output from scanning (from spotter scan CLI command).'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cli_version }}
    - ${{ inputs.paths }}
    - ${{ inputs.parse_values }}
    - ${{ inputs.display_level }}
    - ${{ inputs.ansible_version }}
